# Generated by Django 4.1.4 on 2022-12-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'databases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pw_username', models.CharField(max_length=32)),
                ('pw_password', models.CharField(max_length=64)),
                ('pw_link', models.CharField(max_length=256)),
                ('pw_note', models.CharField(max_length=128)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pw_man.databases')),
            ],
            options={
                'db_table': 'passwords',
                'managed': True,
            },
        ),
    ]
