# Generated by Django 4.1.4 on 2023-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
