# Generated by Django 4.1.4 on 2023-01-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pw_man', '0002_databases_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databases',
            old_name='id',
            new_name='db_id',
        ),
        migrations.RenameField(
            model_name='passwords',
            old_name='id',
            new_name='pw_id',
        ),
    ]
